name: Deploy Website

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Write gitinfo file
        run: |
          git tag
          bin/gitversion.sh ${{ github.ref }} ${{ github.sha }} "${{ github.workflow }}"
          cat data/gitinfo.yml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: |
          hugo --baseURL "https://modulehandbook.github.io/staging/"

      - name: Deploy to Production on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh_pages_generated_site
          commit_message: "${{ github.ref }} ${{ github.event.head_commit.message }}"
