name: Deploy Staging

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Write gitinfo file
        run: |
          bin/gitversion.sh ${{ github.ref }} ${{ github.sha }} "${{ github.workflow }}"
          cat data/gitinfo.yml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: |
          hugo --buildDrafts

      - name: Deploy to Staging Drafts on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        # https://github.com/peaceiris/actions-gh-pages
        # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token
        with:
          # generate token with suitable access rights at
          # https://github.com/settings/tokens
          personal_token: ${{ secrets.STAGING_TOKEN }}
          external_repository: modulehandbook/staging
          publish_dir: ./public
          publish_branch: gh_pages_generated_site
          commit_message: ${{ github.event.head_commit.message }}
